const Product = require('../model/product');

exports.getAddProduct =(req,res,next)=>{
    res.render('admin/edit-product',{
        pageTitle: "Add new Product", 
        path: "/admin/add-product",
        editing: false
    });
}

//CALLBACK FUNCTION FOR ADD PRODUCT ROUTE
exports.postAddProduct = (req , res, next) => {
    const {title, imageUrl, price, description } = req.body;
    return new Product(title,price,description,imageUrl,null,req.user._id).save().then(
        result =>{
            console.log(result);
            res.redirect("/");
        }
    ).catch(e=>console.log(e)); 
}

//CALLBACK FUNCTION FOR EDIT PRODUCT ROUTE
exports.getEditProduct =(req,res,next)=>{
    const editMode = req.query.edit;
    if(!editMode){
        return res.redirect('/');
    }
    const prodId = req.params.productId;
    //HELPER METHOD GENERATED BY SEQUELIZE
    Product.findById(prodId).then(product=>{
        if(!product){
            return  res.redirect('/');
         }
         res.render('admin/edit-product',{ 
             pageTitle: "Edit Product", 
             path: "/admin/edit-product",
             editing: true,
             product : product
         });
    }).catch(e=>console.log(e));
}

exports.postEditProduct =(req,res,next)=>{
    const {productId, title,price,imageUrl, description } = req.body;
    return new Product(title,price,description,imageUrl,productId,null).save()
    .then(result => {
        console.log('updated');
        res.redirect("/admin/products")
    }).catch(e=>console.log(e))
}

exports.postDeleteProduct = (req, res, next) =>{
    const prodId = req.body.productId;
    Product.deleteById(prodId).then(p=>res.redirect('/admin/products')).catch(e=>console.log(e))
}

exports.getProducts = (req,res,next)=>{

    Product.fetchAll().then(products=>{
 
        res.render("admin/products",
            {
            prods: products , 
            pageTitle :'Admin Products', 
            path:'/admin/products',  
        });
    }).catch(e=>console.log(e));
}