const Product = require('../model/product');
const { validationResult } = require('express-validator')

exports.getAddProduct =(req,res,next)=>{

    res.render('admin/edit-product',{
        pageTitle: "Add new Product", 
        path: "/admin/add-product",
        editing: false,
        hasError : false,
        errorMessage : null,
        validationErrors :[]
        // isAuthenticated : req.session.isLoggedIn  
    });
}

//CALLBACK FUNCTION FOR ADD PRODUCT ROUTE
exports.postAddProduct = (req , res, next) => {
    const {title, imageUrl, price, description } = req.body;
    const errors = validationResult(req)

    if(!errors.isEmpty()){
        console.log(errors.array())
       return res.status(422).render('admin/edit-product',{ 
            pageTitle: "Add Product", 
            path: "/admin/edit-product",
            editing: false,
            hasError : true,
            product : {
                title : title,
                imageUrl : imageUrl,
                price : price,
                description : description
            },
            errorMessage : errors.array()[0].msg,
            validationErrors :errors.array()
        });
    }

    return new Product({title: title, imageUrl: imageUrl, description : description, price : price, userId: req.user._id}).save().then(
        result =>{
            console.log(result);
            res.redirect("/");
        }
    ).catch(e=>{
        const error = new Error(e)
        error.httpStatusCode = 500
        next(error);
        console.log(e); res.redirect('/500')
    }); 
}

//CALLBACK FUNCTION FOR EDIT PRODUCT ROUTE
exports.getEditProduct =(req,res,next)=>{
    const editMode = req.query.edit;
    if(!editMode){
        return res.redirect('/');
    }
    const prodId = req.params.productId;
    //HELPER METHOD GENERATED BY SEQUELIZE
    Product.findById(prodId).then(product=>{
        //throw new Error('Maddo')
        if(!product){
            return  res.redirect('/');
         }
         res.render('admin/edit-product',{ 
             pageTitle: "Edit Product", 
             path: "/admin/edit-product",
             editing: true,
             product : product ,
             hasError : false,
             errorMessage : null,validationErrors :[]
         });
    }).catch(e=>{
        const error = new Error(e)
        error.httpStatusCode = 500
        next(error);
        console.log(e); res.redirect('/500')
    });
}

exports.postEditProduct =(req,res,next)=>{ 
    const {productId, title,price,imageUrl, description } = req.body;
    const errors = validationResult(req)

    if(!errors.isEmpty()){
        console.log(errors.array())
       return res.status(422).render('admin/edit-product',{ 
            pageTitle: "Edit Product", 
            path: "/admin/edit-product",
            editing: true,
            hasError : true,
            product : {
                title : title,
                imageUrl : imageUrl,
                price : price,
                description : description,
                _id : productId
            },
            errorMessage : errors.array()[0].msg,
            validationErrors :errors.array()
        });
    }

    Product.findById(productId).then(
        product =>{
            if(product.userId.toString()!== req.user._id.toString()){
                return res.redirect('/')
            }
            product.title =title;
            product.price = price;
            product.description = description;
            product.imageUrl = imageUrl
            //calling save here on document that already exists does an update in mongoose
            return product.save().then(result => {
                console.log('updated');
                res.redirect("/admin/products")
            }).catch(e=>console.log(e))
        }
    )
    .catch(e=>{
        const error = new Error(e)
        error.httpStatusCode = 500
        next(error);
        console.log(e); res.redirect('/500')
    });
}

exports.postDeleteProduct = (req, res, next) =>{
    const prodId = req.body.productId;
    Product.deleteOne({_id :prodId, userId: req.user._id}).then(p=>res.redirect('/admin/products')).catch(e=>{
        const error = new Error(e)
        error.httpStatusCode = 500
        next(error);
        console.log(e); res.redirect('/500')
    });
}

exports.getProducts = (req,res,next)=>{
    //select method works like projection
    //.populate('userId','name email') is used to pull data in relational collection referenced
    //the first argument passed to populate is the field that needs to be populated
    //the second argument passed to populate is projection
    Product.find({userId : req.user._id})
    //.select('title price ').populate('userId', 'name')
    .then(products=>{
        console.log(products);
        res.render("admin/products",
            {
            prods: products , 
            pageTitle :'Admin Products', 
            path:'/admin/products' 
        });
    }).catch(e=>{
        const error = new Error(e)
        error.httpStatusCode = 500
        next(error);
        console.log(e); res.redirect('/500')
    });
}